version: '3'
services:
  vite-app:
    image: daily-tales-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5173:5173'

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vite-app
