openapi: 3.0.1
info:
  title: 하루한글 API
  description: 하루한글 API 명세입니다.
  version: 0.0.1
servers:
  - url: https://localhost:8080
tags: []
paths:
  /api/me/writings:
    get:
      tags:
        - 내 글 관리
      summary: 글 목록 조회 API
      description: 글 목록 조회 API 입니다.
      operationId: 글 목록 조회 API
      parameters:
        - name: end-date
          in: query
          description: '종료 (기본값 : 오늘'
          required: true
          schema:
            type: string
        - name: start-date
          in: query
          description: '시작 날짜 (기본값 : 오늘)'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/글 목록 조회 응답'
              examples:
                글 목록 조회 API:
                  value:
                    "{\n  \"writings\" : [ {\n    \"id\" : \"writing_id1\",\n\
                    \    \"title\" : \"title1\",\n    \"visibility\" : \"PUBLIC\"\
                    ,\n    \"writtenAt\" : \"2024-07-15\"\n  }, {\n    \"id\" : \"\
                    writing_id2\",\n    \"title\" : \"title2\",\n    \"visibility\"\
                    \ : \"PUBLIC\",\n    \"writtenAt\" : \"2024-07-15\"\n  }, {\n\
                    \    \"id\" : \"writing_id3\",\n    \"title\" : \"title3\",\n\
                    \    \"visibility\" : \"PRIVATE\",\n    \"writtenAt\" : \"2024-07-15\"\
                    \n  } ]\n}"
    post:
      tags:
        - 내 글 관리
      summary: 글 등록 API
      description: 글 등록 API 입니다.
      operationId: 글 등록 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/글 작성 요청'
            examples:
              글 등록 API:
                value:
                  "{\n  \"title\" : \"title\",\n  \"keywords\" : [ \"keyword1\"\
                  , \"keyword2\" ],\n  \"content\" : \"content\",\n  \"commentary\"\
                  \ : \"commentary\"\n}"
      responses:
        '200':
          description: '200'
  /api/oauth/google:
    post:
      tags:
        - 인증
      summary: 구글 OAuth 인증 API
      description: 구글 OAuth 인증 API 입니다.
      operationId: 구글 로그인 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/로그인 요청'
            examples:
              구글 로그인 API:
                value: "{\n  \"access_token\" : \"access_token\"\n}"
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/로그인 응답'
              examples:
                구글 로그인 API:
                  value:
                    "{\n  \"access_token\" : \"access_token\",\n  \"refresh_token\"\
                    \ : \"refresh_token\"\n}"
  /api/oauth/kakao:
    post:
      tags:
        - 인증
      summary: 카카오 OAuth 인증 API
      description: 카카오 OAuth 인증 API 입니다.
      operationId: 카카오 로그인 API
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/로그인 요청'
            examples:
              카카오 로그인 API:
                value: "{\n  \"access_token\" : \"access_token\"\n}"
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/로그인 응답'
              examples:
                카카오 로그인 API:
                  value:
                    "{\n  \"access_token\" : \"access_token\",\n  \"refresh_token\"\
                    \ : \"refresh_token\"\n}"
  /api/me/writings/statistics/main-keywords:
    get:
      tags:
        - 글 통계
      summary: 메인 키워드 조회 API
      description: 메인 키워드 조회 API 입니다.
      operationId: 메인 키워드 조회 API
      parameters:
        - name: size
          in: query
          description: 조회할 메인 키워드 개수
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/메인 키워드 조회 응답'
              examples:
                메인 키워드 조회 API:
                  value:
                    "{\n  \"main_keywords\" : [ {\n    \"keyword\" : \"keyword1\"\
                    ,\n    \"frequency\" : 1\n  }, {\n    \"keyword\" : \"keyword2\"\
                    ,\n    \"frequency\" : 2\n  } ]\n}"
  /api/me/writings/statistics/published-writings:
    get:
      tags:
        - 글 통계
      summary: 작성한 글 수 조회 API
      description: 작성한 글 수 조회 API 입니다.
      operationId: 작성한 글 수 조회 API
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/작성한 글 수 조회 응답'
              examples:
                작성한 글 수 조회 API:
                  value: "{\n  \"published_writings\" : 0\n}"
  /api/me/writings/statistics/total-writings-per-day:
    get:
      tags:
        - 글 통계
      summary: 일별 글 작성 통계 조회 API
      description: |-
        일별 글 작성 통계 조회 API 입니다.
        1일부터 선택한 월의 마지막 날까지의 글 작성 통계를 조회합니다.
      operationId: 일별 글 작성 통계 조회 API
      parameters:
        - name: month
          in: query
          description: 조회할 월
          required: true
          schema:
            type: string
        - name: year
          in: query
          description: 조회할 연도
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/일별 글 작성 통계 조회 응답'
              examples:
                일별 글 작성 통계 조회 API:
                  value:
                    "{\n  \"total_writings_per_day\" : [ 1, 1, 1, 1, 1, 1, 1,\
                    \ 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,\
                    \ 1, 1, 1, 1 ]\n}"
  /api/me/writings/statistics/total-writings-per-month:
    get:
      tags:
        - 글 통계
      summary: 월별 글 작성 통계 조회 API
      description: 월별 글 작성 통계 조회 API 입니다.
      operationId: 월별 글 작성 통계 조회 API
      parameters:
        - name: year
          in: query
          description: 조회할 연도
          required: true
          schema:
            type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/월별 글 작성 통계 조회 응답'
              examples:
                월별 글 작성 통계 조회 API:
                  value:
                    "{\n  \"total_writings_of_year\" : 12,\n  \"total_writings_per_month\"\
                    \ : {\n    \"JANUARY\" : 1,\n    \"FEBRUARY\" : 1,\n    \"MARCH\"\
                    \ : 1,\n    \"APRIL\" : 1,\n    \"MAY\" : 1,\n    \"JUNE\" : 1,\n\
                    \    \"JULY\" : 1,\n    \"AUGUST\" : 1,\n    \"SEPTEMBER\" : 1,\n\
                    \    \"OCTOBER\" : 1,\n    \"NOVEMBER\" : 1,\n    \"DECEMBER\"\
                    \ : 1\n  }\n}"
  /api/me/writings/{id}/commentary:
    patch:
      tags:
        - 내 글 관리
      summary: 글 감상문 수정 API
      description: 글 감상문 수정 API 입니다.
      operationId: 글 감상문 수정 API
      parameters:
        - name: id
          in: path
          description: 글 ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/감상문 수정 요청'
            examples:
              글 감상문 수정 API:
                value: "{\n  \"commentary\" : \"commentary\"\n}"
      responses:
        '200':
          description: '200'
  /api/me/writings/{id}/visibility:
    patch:
      tags:
        - 내 글 관리
      summary: 글 공유 범위 수정 API
      description: "글 공유 범위 수정 API 입니다.\n공유 범위 : PUBLIC, PRIVATE"
      operationId: 글 공유 범위 수정 API
      parameters:
        - name: id
          in: path
          description: 글 ID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/글 공유 범위 수정 요청'
            examples:
              글 공유 범위 수정 API:
                value: "{\n  \"visibility\" : \"PUBLIC\"\n}"
      responses:
        '200':
          description: '200'
components:
  schemas:
    글 목록 조회 응답:
      title: 글 목록 조회 응답
      type: object
      properties:
        writings:
          type: array
          items:
            type: object
            properties:
              writtenAt:
                type: string
                description: 글 작성일
              visibility:
                type: string
                description: 글 공개 범위
              id:
                type: string
                description: 글 ID
              title:
                type: string
                description: 글 제목
    로그인 응답:
      title: 로그인 응답
      type: object
      properties:
        access_token:
          type: string
          description: 액세스 토큰
        refresh_token:
          type: string
          description: 리프레시 토큰
    로그인 요청:
      title: 로그인 요청
      type: object
      properties:
        access_token:
          type: string
          description: 인증 코드
    메인 키워드 조회 응답:
      title: 메인 키워드 조회 응답
      type: object
      properties:
        main_keywords:
          type: array
          items:
            type: object
            properties:
              keyword:
                type: string
                description: 메인 키워드
              frequency:
                type: number
                description: 키워드 등장 횟수
    일별 글 작성 통계 조회 응답:
      title: 일별 글 작성 통계 조회 응답
      type: object
      properties:
        total_writings_per_day:
          type: array
          description: 일마다 작성한 글 수
          items:
            oneOf:
              - type: object
              - type: boolean
              - type: string
              - type: number
    월별 글 작성 통계 조회 응답:
      title: 월별 글 작성 통계 조회 응답
      type: object
      properties:
        total_writings_per_month:
          type: object
          properties:
            JUNE:
              type: number
              description: 6월 작성 글 수
            JANUARY:
              type: number
              description: 1월 작성 글 수
            MAY:
              type: number
              description: 5월 작성 글 수
            OCTOBER:
              type: number
              description: 10월 작성 글 수
            DECEMBER:
              type: number
              description: 12월 작성 글 수
            MARCH:
              type: number
              description: 3월 작성 글 수
            AUGUST:
              type: number
              description: 8월 작성 글 수
            FEBRUARY:
              type: number
              description: 2월 작성 글 수
            SEPTEMBER:
              type: number
              description: 9월 작성 글 수
            JULY:
              type: number
              description: 7월 작성 글 수
            NOVEMBER:
              type: number
              description: 11월 작성 글 수
            APRIL:
              type: number
              description: 4월 작성 글 수
        total_writings_of_year:
          type: number
          description: 연간 작성한 글의 갯수
    감상문 수정 요청:
      title: 감상문 수정 요청
      type: object
      properties:
        commentary:
          type: string
          description: 감상문
    글 공유 범위 수정 요청:
      title: 글 공유 범위 수정 요청
      type: object
      properties:
        visibility:
          type: string
          description: 글의 공유 범위
    글 작성 요청:
      title: 글 작성 요청
      type: object
      properties:
        keywords:
          type: array
          description: 글의 주요 키워드
          items:
            oneOf:
              - type: object
              - type: boolean
              - type: string
              - type: number
        title:
          type: string
          description: 글의 제목
        commentary:
          type: string
          description: 감상문
        content:
          type: string
          description: 글의 내용
    작성한 글 수 조회 응답:
      title: 작성한 글 수 조회 응답
      type: object
      properties:
        published_writings:
          type: number
          description: 작성한 글 수
